[target.armv7-unknown-linux-gnueabihf]
# The following lines can be uncommented to use a native
# ARM image when compiling on a ARM machine, like the new Apple devices.
#
# This needs the master version of cross (as of 2023-02-05).

#image.name = "ahuszagh/aarch64-cross:armv7-unknown-linux-gnueabihf"
#image.toolchain = ["aarch64-unknown-linux-gnu"]
pre-build = [
    "dpkg --add-architecture armhf",
    "apt-get update",
    "apt-get install --assume-yes libusb-1.0-0-dev:armhf libftdi1-dev:armhf libudev-dev:armhf libssl-dev:armhf",
]

[target.aarch64-unknown-linux-gnu]
# The following lines can be uncommented to use a native
# ARM image when compiling on a ARM machine, like the new Apple devices.
#
# This needs the master version of cross (as of 2023-02-05).

# image.name = "ahuszagh/aarch64-cross:aarch64-unknown-linux-gnu"
# image.toolchain = ["aarch64-unknown-linux-gnu"]
pre-build = [
    "apt-get update",
    "apt-get install --assume-yes libusb-1.0-0-dev libftdi1-dev libudev-dev libssl-dev",
]
