
on:
  push:
    branches: [master, staging, trying]
  pull_request:
  merge_group:


name: Run smoke test

env:
  CARGO_INCREMENTAL: 0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install libusb, libudev (linux)
        run: |
          sudo dpkg --add-architecture arm64
          sudo apt update
          sudo apt install -y libusb-1.0-0-dev:arm64 libudev-dev:arm64

      - uses: ./.github/actions/setup
        with:
          targets:
            aarch64-unknown-linux-gnu

      - name: Install cross 
        uses: taiki-e/install-action@v2.4.2
        with:
          tool: cross

      - name: Cache Dependencies
        uses: Swatinem/rust-cache@v2.2.0
      
      - name: Build smoke-tester
        run:
          cross build --release --target aarch64-unknown-linux-gnu -p smoke_tester
      
      - uses: actions/upload-artifact@v3
        with:
          name: smoke_tester
          path: target/aarch64-unknown-linux-gnu/release/smoke_tester

      

